services:
  proxy:
    image: nginx:1.25.4-alpine3.18
    volumes:
      - /home/vv173/Development/material-applications/proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - frontend
      - backend
    depends_on: 
      - frontend
  frontend:
    build:
      context: ./example-frontend/
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKENDURL=http://backend:8080
    depends_on:
      - backend
    networks:
      - backend
  backend:
    build:
      context: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=db
    networks:
      - backend
      - frontend
    depends_on:
      - db
  redis:
    image: redis:7.2.4
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  frontend:
  backend:
volumes:
  db-data:
